---
- name: Install and start nginx
  hosts: dbservers
  become: true
  become_user: root

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started
